services:
  # Backend Web Service
  - type: web
    name: live-polling-backend
    env: node
    plan: free
    buildCommand: cd backend && npm install
    startCommand: cd backend && npm start
    healthCheckPath: /api/health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        fromService:
          type: web
          name: live-polling-backend
          property: port
      - key: FRONTEND_URL
        fromService:
          type: web
          name: live-polling-frontend
          property: url

  # Frontend Static Site
  - type: web
    name: live-polling-frontend
    env: static
    plan: free
    buildCommand: cd frontend && npm install && npm run build
    staticPublishPath: ./frontend/build
    pullRequestPreviewsEnabled: false
    envVars:
      - key: NODE_ENV
        value: production
      - key: REACT_APP_API_URL
        fromService:
          type: web
          name: live-polling-backend
          property: url
      - key: REACT_APP_SOCKET_URL
        fromService:
          type: web
          name: live-polling-backend
          property: url

# Database (if you want to add PostgreSQL later)
# databases:
#   - name: live-polling-db
#     plan: free