services:
  # Backend Web Service
  - type: web
    name: live-polling-backend
    env: node
    plan: starter
    buildCommand: cd backend && npm install
    startCommand: cd backend && npm start
    healthCheckPath: /api/health
    envVars:
      - key: NODE_ENV
        value: production
      - key: FRONTEND_URL
        value: https://live-polling-frontend.onrender.com

  # Frontend Static Site
  - type: web
    name: live-polling-frontend
    env: static
    plan: starter
    buildCommand: cd frontend && npm install && npm run build
    staticPublishPath: ./frontend/build
    pullRequestPreviewsEnabled: false
    envVars:
      - key: NODE_ENV
        value: production
      - key: REACT_APP_API_URL
        value: https://live-polling-backend.onrender.com
      - key: REACT_APP_SOCKET_URL
        value: https://live-polling-backend.onrender.com

# Database (if you want to add PostgreSQL later)
# databases:
#   - name: live-polling-db
#     plan: free